### PR TITLE
bug_fix_2174

### PR DESCRIPTION
**Pull request by SadiHassan**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...
bug_fix_2174

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Review by ltrk2 — CHANGES_REQUESTED** [review]
If I switch the query around and run `print x = (1d + 1d) | where "asd" !~ tostring(x);` then it still doesn't work.

Also, it introduces a regression: `print 'asd' !~ 1;` isn't supposed to work (error `Cannot perform 'NotEqualIgnoreCase' operation for values of types long and string. Try adding explicit casts` in ADX, but it does with your solution.

I believe that the issue is with the parsing, so please kindly focus on that part.

**Comment by SadiHassan** [comment]
@ltrk2 May be it's required, because this PR has other improvements than single/double quotes recognition.

**Comment by ltrk2** [comment]
@SadiHassan you can close the PR and the changes will still be present on the feature branch, should you ever need them.

**Comment by SadiHassan** [comment]
Closing this and will submit a new PR after rework.

**Pull request closed without merging**
